### ISSUE TITLE
No way to contribute

### ISSUE THREAD

**Issue by djack42** [microsoft/MSBuildCache#106]
Hi,
The nuget feed is preventing me to restore and build the repository.
I can list the feed but have no rights to download the packages.

> The feed 'msbuildcache [https://pkgs.dev.azure.com/msbuildcache/public/_packaging/msbuildcache/nuget/v3/index.json]' lists package 'Azure.Storage.Blobs.12.13.0' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again.

**Comment by Cjewett** [comment]
I created a list of issues I had to fix to compile locally here: https://github.com/microsoft/MSBuildCache/issues/107

**Comment by djack42** [comment]
That fixed my compilation problems, thank you.

> I created a list of issues I had to fix to compile locally here: [#107](https://github.com/microsoft/MSBuildCache/issues/107)
