### ISSUE TITLE
Plugin causes subsequent builds to fail by trying to open CacheClient.log log again

### ISSUE THREAD

**Issue by AArnott** [microsoft/MSBuildCache#85]
The first build is fine, except that the CacheClient.log file remains locked, as evident by failed attempts to delete it, and subsequent attempts to build failing with:

> MSBUILD : warning : BeginBuildAsync failed after 14 ms: System.IO.IOException: The process cannot access the file 'CacheClient.log' because it is being used by another process.

**Comment by dfederm** [comment]
Note to self from investigation: We dispose the BXL `Logger` object, but that apparently doesn't dispose the underlying `ILog` instances (`FileLog` in our case), leading to the log file handle not being closed.
