### ISSUE TITLE
Cache misses when a build request for a cross-targeting project without preceding per-TF requests

### ISSUE THREAD

**Issue by AArnott** [microsoft/MSBuildCache#86]
A non-graph-based build scheduler may ask for projects to build in topographical order without awareness of `TargetFramework` global properties that may apply. When a cross-targeting project's build is requested, its "dependencies" include the per-TargetFramework projects, and if they were not built previously, the plugin reports a cache miss.

I expect/hope that instead, the plugin can replay the cache from each TargetFramework in the project if necessary so that the whole project's output can be reconstituted as would happen without the cache.

**Comment by dfederm** [comment]
This was fixed by #93. However, note that the `$(MSBuildCacheGetResultsForUnqueriedDependencies)` property (or `GetResultsForUnqueriedDependencies` setting on the plugin) must be set to opt-into this behavior.
